# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    kinova_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    kinova_arm_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    skratch_base_controller:
      type: velocity_controllers/JointGroupVelocityController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

kinova_arm_controller:
  ros__parameters:
    joints:
      - shoulder_joint
      - half_arm_one_joint
      - half_arm_two_joint
      - fore_arm_joint
      - spherical_wrist_one_joint
      - spherical_wrist_two_joint
      - camera_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
kinova_arm_gripper_controller:
  ros__parameters:
    joints:
      - gripper_left_knuckle_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity

skratch_base_controller:
  ros__parameters:
    joints:
      - front_left_drive_left_hub_wheel_joint
      - front_left_drive_right_hub_wheel_joint
      - front_right_drive_left_hub_wheel_joint
      - front_right_drive_right_hub_wheel_joint
      - rear_left_drive_left_hub_wheel_joint
      - rear_left_drive_right_hub_wheel_joint
      - rear_right_drive_left_hub_wheel_joint
      - rear_right_drive_right_hub_wheel_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
