controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    skratch_base_wheel_controller:
      type: velocity_controllers/JointGroupVelocityController

skratch_base_wheel_controller:
  ros__parameters:
    joints:
      - front_left_drive_left_hub_wheel_joint
      - front_left_drive_right_hub_wheel_joint
      - front_right_drive_left_hub_wheel_joint
      - front_right_drive_right_hub_wheel_joint
      - rear_left_drive_left_hub_wheel_joint
      - rear_left_drive_right_hub_wheel_joint
      - rear_right_drive_left_hub_wheel_joint
      - rear_right_drive_right_hub_wheel_joint

    command_interfaces:
      - velocity

    state_interfaces:
      - velocity
      - position
